apiVersion: 1
kind: Node
metadata:
  name: worker-node
  labels:
    # Use labels to organize nodes
    environment: dev
  spec:
    # Fully qualified domain name to reach the node (metadata.name by default)
    externalID: k8s-node